### ISSUE TITLE
ERROR in Error: Metadata version mismatch for module

### ISSUE THREAD

**Issue by qadeerqureshi** [DanielYKPan/date-time-picker#274]
Hi, I am using 5.1.6 version. Here is detail of my angular app dependency. Please help me with this problem thanks!

Angular modules and versions.

    "@angular/animations": "^4.4.6",
    "@angular/cdk": "^5.2.1",
    "@angular/common": "^4.4.6",
    "@angular/compiler": "^4.4.6",
    "@angular/core": "^4.4.6",
    "@angular/forms": "^4.4.6",
    "@angular/http": "^4.4.6",
    "@angular/platform-browser": "^4.4.6",
    "@angular/platform-browser-dynamic": "^4.4.6",
    "@angular/router": "^4.4.6",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.5",

`ERROR in Error: Metadata version mismatch for module C:/Users/Sami/Documents/cloud2_client/node_modules/ng-pick-datetime/date-time/index.d.ts, found version 4, expected 3, resolving symb
ol SystemModule in C:/Users/Sami/Documents/cloud2_client/src/app/systems/system.module.ts, resolving symbol SystemModule in C:/Users/Sami/Documents/cloud2_client/src/app/systems/system.m
odule.ts
    at syntaxError (C:\Users\Sami\Documents\cloud2_client\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at simplifyInContext (C:\Users\Sami\Documents\cloud2_client\node_modules\@angular\compiler\bundles\compiler.umd.js:24979:23)
    at StaticReflector.simplify (C:\Users\Sami\Documents\cloud2_client\node_modules\@angular\compiler\bundles\compiler.umd.js:24991:13)
    at StaticReflector.annotations (C:\Users\Sami\Documents\cloud2_client\node_modules\@angular\compiler\bundles\compiler.umd.js:24418:41)
    at _getNgModuleMetadata (C:\Users\Sami\Documents\cloud2_client\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (C:\Users\Sami\Documents\cloud2_client\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at C:\Users\Sami\Documents\cloud2_client\node_modules\@angular\compiler-cli\src\ngtools_impl.js:129:27
    at Array.reduce (<anonymous>)
    at _extractLazyRoutesFromStaticModule (C:\Users\Sami\Documents\cloud2_client\node_modules\@angular\compiler-cli\src\ngtools_impl.js:128:10)
    at Object.listLazyRoutesOfModule (C:\Users\Sami\Documents\cloud2_client\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\Users\Sami\Documents\cloud2_client\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (C:\Users\Sami\Documents\cloud2_client\node_modules\@ngtools\webpack\src\plugin.js:212:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (C:\Users\Sami\Documents\cloud2_client\node_modules\@ngtools\webpack\src\plugin.js:448:24)
    at <anonymous>
`

**Comment by poojatak** [comment]
I updated angular 4 to 5 but still getting same issue
![package](https://user-images.githubusercontent.com/36785951/36627108-e00a500e-1963-11e8-98ab-f8402e07c1bc.png)

**Comment by DanielYKPan** [comment]
update you angular cli version

**Comment by poojatak** [comment]
Thanks for instant reply :)

**Comment by naveenr2112** [comment]
![screenshot_7](https://user-images.githubusercontent.com/14159191/37048361-b16a1df0-2193-11e8-8e71-1642d3085af9.png)

Using the above dependencies.

**Comment by DanielYKPan** [comment]
It only supports Angular 5+

**Comment by naveenr2112** [comment]
@DanielYKPan Thanks for the Reply. Will upgrade to Angular 5!
