### ISSUE TITLE
Version Mismatch Error : /ui/node_modules/ng-pick-datetime/picker.d.ts, found version 4, expected 3, resolving symbol AppModule in C

### ISSUE THREAD

**Issue by siva563** [DanielYKPan/date-time-picker#353]
Hi Team, I am facing Version Issue,

I am Using Angular : ` "@angular/animations": "^4.4.7",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "@swimlane/ngx-datatable": "^11.2.0",
    "@types/moment": "^2.13.0",
    "babel-polyfill": "^6.26.0",
    "bootstrap-sass": "^3.3.7",
    "core-js": "^2.4.1",
    "crypto-js": "^3.1.9-1",
    "font-awesome": "^4.7.0",
    "intl": "^1.2.5",
    "jquery": "^3.2.1",
    "moment": "^2.22.0",
    "ng-pick-datetime": "^5.2.6",
    "ng2-date-picker": "^2.9.0",
    "ng4-social-login": "^1.3.5",
    "ngx-bootstrap": "^2.0.2",
    "ngx-facebook": "^2.4.0",
    "ngx-file-drop": "^2.0.5",
    "popper.js": "^1.12.5",
    "rxjs": "^5.4.2",
    "string.prototype.contains": "^0.2.0",
    "string.prototype.endswith": "^0.2.0",
    "string.prototype.startswith": "^0.2.0",
    "zone.js": "^0.8.14"`

I am getting below Error:

`ERROR in Error: Metadata version mismatch for module C:/Users/Sivaprasad/git/ppms1/ppms-root/app/ppms-ui/ui/node_modules/ng-pick-datetime/picker.d.ts, found version 4, expected 3, resolving symbol AppModule in C:/Users/Sivaprasad/git/ppms1/ppms-root/app/ppms-ui/ui/src/app/app.module.ts, resolving symbol AppModule in C:/Users/Sivaprasad/git/ppms1/ppms-root/app/ppms-ui/ui/src/app/app.module.ts
    at syntaxError (C:\Users\Sivaprasad\git\ppms1\ppms-root\app\ppms-ui\ui\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at simplifyInContext (C:\Users\Sivaprasad\git\ppms1\ppms-root\app\ppms-ui\ui\node_modules\@angular\compiler\bundles\compiler.umd.js:24979:23)
    at StaticReflector.simplify (C:\Users\Sivaprasad\git\ppms1\ppms-root\app\ppms-ui\ui\node_modules\@angular\compiler\bundles\compiler.umd.js:24991:13)
    at StaticReflector.annotations (C:\Users\Sivaprasad\git\ppms1\ppms-root\app\ppms-ui\ui\node_modules\@angular\compiler\bundles\compiler.umd.js:24418:41)
    at _getNgModuleMetadata (C:\Users\Sivaprasad\git\ppms1\ppms-root\app\ppms-ui\ui\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (C:\Users\Sivaprasad\git\ppms1\ppms-root\app\ppms-ui\ui\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (C:\Users\Sivaprasad\git\ppms1\ppms-root\app\ppms-ui\ui\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\Users\Sivaprasad\git\ppms1\ppms-root\app\ppms-ui\ui\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (C:\Users\Sivaprasad\git\ppms1\ppms-root\app\ppms-ui\ui\node_modules\@ngtools\webpack\src\plugin.js:212:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (C:\Users\Sivaprasad\git\ppms1\ppms-root\app\ppms-ui\ui\node_modules\@ngtools\webpack\src\plugin.js:448:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

**Comment by siva563** [comment]
@DanielYKPan , help is required appreciated. Thanks !!!

**Comment by DanielYKPan** [comment]
This picker supports only Angular 6+
