### ISSUE TITLE
support  angular 6 ng-pick-datetime-moment

### ISSUE THREAD

**Issue by vatsaldashani** [DanielYKPan/date-time-picker#529]
i used ng-pick-datetime-moment  in angular 6 
after this package install they will be dispaly error 

`
> node-sass@4.9.3 install /home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/@angular-devkit/build-angular/node_modules/node-sass
> node scripts/install.js

Unable to save binary /home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/@angular-devkit/build-angular/node_modules/node-sass/vendor/linux-x64-57 : { Error: EACCES: permission denied, mkdir '/home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/@angular-devkit/build-angular/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/@angular-devkit/build-angular/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/@angular-devkit/build-angular/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/@angular-devkit/build-angular/node_modules/node-sass/vendor' }

> node-sass@4.9.4 install /home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/node-sass
> node scripts/install.js

Unable to save binary /home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/node-sass/vendor/linux-x64-57 : { Error: EACCES: permission denied, mkdir '/home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/node-sass/vendor' }

> node-sass@4.9.3 postinstall /home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/@angular-devkit/build-angular/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/node /home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@8.11.3 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.15
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 8.11.3
gyp verb command install [ '8.11.3' ]
gyp verb install input version string "8.11.3"
gyp verb install installing version: 8.11.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.11.3
gyp verb build dir attempting to create "build" dir: /home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/@angular-devkit/build-angular/node_modules/node-sass/build
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/@angular-devkit/build-angular/node_modules/node-sass/build'
gyp ERR! System Linux 4.15.0-38-generic
gyp ERR! command "/usr/bin/node" "/home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/@angular-devkit/build-angular/node_modules/node-sass
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1

> node-sass@4.9.4 postinstall /home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/node /home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@8.11.3 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.15
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 8.11.3
gyp verb command install [ '8.11.3' ]
gyp verb install input version string "8.11.3"
gyp verb install installing version: 8.11.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.11.3
gyp verb build dir attempting to create "build" dir: /home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/node-sass/build
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/node-sass/build'
gyp ERR! System Linux 4.15.0-38-generic
gyp ERR! command "/usr/bin/node" "/home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/protl-vatsal/Documents/vatsal_workspace/PERFEQTA4/perfeqta4-web/node_modules/node-sass
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN @angular/flex-layout@7.0.0-beta.19 requires a peer of @angular/cdk@^7.0.0-rc.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/flex-layout@7.0.0-beta.19 requires a peer of @angular/core@>=7.0.0-rc.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/flex-layout@7.0.0-beta.19 requires a peer of @angular/common@>=7.0.0-rc.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@6.0.8 requires a peer of typescript@~2.4.0 || ~2.5.0 || ~2.6.0 || ~2.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular2-mentions@0.7.3 requires a peer of @angular/common@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular2-mentions@0.7.3 requires a peer of @angular/core@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-expression-builder@5.0.1 requires a peer of @angular/common@^5.2.10 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-expression-builder@5.0.1 requires a peer of @angular/core@^5.2.10 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-expression-builder@5.0.1 requires a peer of @angular/cdk@^5.2.5 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-expression-builder@5.0.1 requires a peer of @angular/material@~5.2.5 but none is installed. You must install peer dependencies yourself.
npm WARN ng-pick-datetime-moment@1.0.8 requires a peer of @angular/animations@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng-pick-datetime-moment@1.0.8 requires a peer of @angular/common@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng-pick-datetime-moment@1.0.8 requires a peer of @angular/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng-pick-datetime-moment@1.0.8 requires a peer of @angular/forms@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng-pick-datetime-moment@1.0.8 requires a peer of ng-pick-datetime@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/forms@7.0.3 requires a peer of @angular/platform-browser@7.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.9.3 (node_modules/@angular-devkit/build-angular/node_modules/node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.9.3 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.4 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.9.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/protl-vatsal/.npm/_logs/2018-11-12T13_30_20_075Z-debug.log
`

**Comment by vatsaldashani** [comment]
please solved my problem
